name: Deploy TaxAppUK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_ROOT: /usr/share/dotnet

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore
        working-directory: .

      - name: Build the solution and publish
        run: dotnet build --no-restore --configuration Release --output ./API/bin/Release/net8.0/publish/
        working-directory: .

      - name: Verify publish output
        run: ls -al ./API/bin/Release/net8.0/publish/

#      - name: Run tests
#        run: dotnet test --no-build --configuration Release --verbosity normal
#        working-directory: .

      - name: Configure Azure Blob settings
        run: |
          echo "AZUREBLOBSETTINGS__BLOBCONNECTIONSTRING=${{ secrets.AZUREBLOBSETTINGS__BLOBCONNECTIONSTRING }}" >> $GITHUB_ENV
          echo "AZUREBLOBSETTINGS__TAXRATESCONTAINERNAME=${{ secrets.AZUREBLOBSETTINGS__TAXRATESCONTAINERNAME }}" >> $GITHUB_ENV
          echo "AZUREBLOBSETTINGS__TAXRATESUKBLOBNAME=${{ secrets.AZUREBLOBSETTINGS__TAXRATESUKBLOBNAME }}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TAXAPPUKSP_AZURE_CREDENTIALS}}

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TaxAppUK-WebApp'
          package: './API/bin/Release/net8.0/publish/' # Use the publish output directory
