name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Specify .NET version
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: dotnet restore
      
      # Step 4: Build the application
      - name: Build application
        run: dotnet build --configuration Release --no-restore
      
      # Step 5: Run tests (optional)
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      
      # Step 6: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
      
      # Step 7: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-app-service-name' # Replace with your App Service name
          package: '.' # Path to the application package
