name: Deploy TaxAppUK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_ROOT: /usr/share/dotnet

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore
        working-directory: .

      - name: Publish the API project for deployment
        # IMPORTANT CHANGE: Use 'dotnet publish' instead of 'dotnet build'
        # We explicitly set stdoutLogEnabled=true via MSBuild property
        run: dotnet publish ./API/API.csproj --no-restore --configuration Release --output ./API/bin/Release/net8.0/publish /p:EnableStdoutLog=true
        working-directory: .

      - name: Verify web.config in publish output (for debugging)
        run: cat ./API/bin/Release/net8.0/publish/web.config
        working-directory: .

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./Tests/UnitTests

      - name: Configure Azure Blob settings
        run: |
          echo "AZUREBLOBSETTINGS__BLOBCONNECTIONSTRING=${{ secrets.AZUREBLOBSETTINGS__BLOBCONNECTIONSTRING }}" >> $GITHUB_ENV
          echo "AZUREBLOBSETTINGS__TAXRATESCONTAINERNAME=${{ secrets.AZUREBLOBSETTINGS__TAXRATESCONTAINERNAME }}" >> $GITHUB_ENV
          echo "AZUREBLOBSETTINGS__TAXRATESUKBLOBNAME=${{ secrets.AZUREBLOBSETTINGS__TAXRATESUKBLOBNAME }}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TAXAPPUKSP_AZURE_CREDENTIALS}}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TaxAppUK-WebApp'
          # Ensure this path matches the output path from 'dotnet publish'
          package: './API/bin/Release/net8.0/publish/'